version: '3'

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: nafrospec
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  backend:
    image: java-docker
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: nafrospec
      MYSQL_PORT: 3306
    depends_on:
      mysqldb:
        condition: service_healthy

  frontend:
    image: frontend-docker
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

